---
title: "Ferraz et al. 2016"
author: "Ben Weinstein"
date: "10/7/2019"
output: 
  html_document:
    toc: true
    number_sections: true
editor_options: 
  chunk_output_type: console
---

# Ferraz et al. 2016 

Ferraz, A., Saatchi, S., Mallet, C., & Meyer, V. (2016). Lidar detection of individual tree size in tropical forests. Remote Sensing of Environment, 183, 318-333.

https://github.com/niknap/MeanShiftR

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Start with default parameters for crown allometry and height. 0.5m canopy height model

```{r}
library(lidR)
library(dplyr)
library(raster)
library(stringr)
#path to evaluation data, assuming Silva2016 folder is the working dir
lidar_tiles<-list.files(full.names=TRUE,"../evaluation/LiDAR/",pattern=".laz")
results<-list()
for(r in lidar_tiles){
  #read file
  las<-readLAS(r)
  
  #Canopy height model
  chm <- grid_canopy(las, res = 0.5, p2r(0.3))
  ker <- matrix(1,3,3)
  chm <- focal(chm, w = ker, fun = mean, na.rm = TRUE)
  
  #Tree top detection 
  ## If there are no trees, this will fail, catch error.
  try( ttops <- tree_detection(chm, lmf(4, 2)), next)
  las   <- lastrees(las, silva2016(chm, ttops))
  
  #extract bounding boxes
  tree_polygons<- tree_hulls(las,type="bbox")
  
  #format bounding boxes
  bboxes<-lapply(tree_polygons@polygons,bbox)
  
  #as a single row
  result<-lapply(bboxes, function(x){
      df<-data.frame(xmin=x["x","min"],ymin=x["y","min"],xmax=x["x","max"],ymax=x["y","max"])
      return(df)
  })
  
  #as a single dataframe
  result<-bind_rows(result)
  
  #add plot name to the first column
  plot_name = str_match(r,"(\\w+).laz")[,2]
  result$plot_name<-plot_name
  result<-result %>% dplyr::select(plot_name,xmin,ymin,xmax,ymax)
  
  results[[r]]<-result 
}

#format for submission by adding
results<-bind_rows(results)
head(results)
write.csv(results,"Silva2016.csv",row.names = FALSE)
```

