#Config file for DeepLidar Tree Demo

#Trained Model Path
model_path: universal_model_july30.h5

#Keras
workers: 1
use_multiprocessing: False
max_queue_size: 20
num_GPUs: 2
save_image_path: /orange/ewhite/b.weinstein/retinanet/
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/
input_channels: 3

#Sliding Window Size and Ovelap
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
  zero_area: True
spatial_filter: True
field_data_path: /home/b.weinstein/DeepLidar/data/field_data.csv

#Select sites
hand_annotation_site:
  - MLBS
pretraining_site:
  - MLBS
evaluation_site:
  - MLBS

#Training
training_images: All
training_proportion: 1
weights: /orange/ewhite/b.weinstein/retinanet/20190719_120823/resnet50_05.h5
imagenet_weights: True
batch_size: 40
epochs: 40
backbone: resnet50
shuffle_training: True
score_threshold: 0.15

#Evaluation
evaluation_images: 0
shuffle_evaluation: False
validation_percent: 5  #For hand annotation neon_MAP

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed. Higher allows more overlap.
nms_threshold: 0.1

#Data Paths
SJER:
  h5: /ufrc/ewhite/b.weinstein/training_h5s/noblending/SJER/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/SJER/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/SJER/training/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/SJER/2018/
  training:
    RGB: /orange/ewhite/NeonData/SJER/DP3.30010.001/2018/FullSite/D17/2018_SJER_3/L3/Camera/Mosaic/V01/
    LIDAR: /orange/ewhite/NeonData/SJER/DP1.30003.001/2018/FullSite/D17/2018_SJER_3/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/SJER/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/SJER/plots/
TEAK:
  h5: /ufrc/ewhite/b.weinstein/training_h5s/noblending/TEAK/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/TEAK/2018/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/TEAK/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/TEAK/training/
  training:
    RGB: /orange/ewhite/NeonData/TEAK/DP3.30010.001/2018/FullSite/D17/2018_TEAK_3/L3/Camera/Mosaic/V01/
    LIDAR: /orange/ewhite/NeonData/TEAK/DP1.30003.001/2018/FullSite/D17/2018_TEAK_3/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/TEAK/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/TEAK/plots/
NIWO:
  h5: /ufrc/ewhite/b.weinstein/training_h5s/noblending/NIWO/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/NIWO/2018/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/NIWO/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/NIWO/training/
  training:
    RGB: /orange/ewhite/NeonData/NIWO/DP3.30010.001/2018/FullSite/D13/2018_NIWO_2/L3/Camera/Mosaic/V01/
    LIDAR: /orange/ewhite/NeonData/NIWO/DP1.30003.001/2018/FullSite/D13/2018_NIWO_2/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/NIWO/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/NIWO/plots/
MLBS:
  h5: /ufrc/ewhite/b.weinstein/training_h5s/noblending/MLBS/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/MLBS/2018/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/MLBS/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/MLBS/training/
  training:
    RGB: /orange/ewhite/NeonData/MLBS/DP3.30010.001/2018/FullSite/D07/2018_MLBS_3/L3/Camera/Mosaic/V01/
    LIDAR: /orange/ewhite/NeonData/MLBS/DP1.30003.001/2018/FullSite/D07/2018_MLBS_3/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/MLBS/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/MLBS/plots/
OSBS:
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/OSBS/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/OSBS/plots/
