---
title: "Loading the dataset in R"
author: "Ben Weinstein"
date: "2/1/2019"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

How to read and view xml annotations from the NEONTreeEvaluation benchmark dataset

```{r, include=FALSE}
library(raster)
source("functions.R")

#Read RGB image as projected raster
rgb<-stack("../SJER/plots/SJER_021.tif")

#Path to dataset
xmls<-readTreeXML(path="../SJER/")

#View one plot's annotations as polygons, project into UTM
#copy project utm zone (epsg), xml has no native projection metadata
xml_polygons <- xml_to_spatial_polygons(xmls[xmls$filename %in% "SJER_021.tif",],rgb)

plotRGB(rgb)
plot(xml_polygons,add=T)
```
# Overlay on imagery

# Open LAS
```{r}
point_cloud<-readLAS("../SJER/plots/SJER_016.laz")
```
Tree annotations are stored in the UserData column. Each tree has a unique numeric ID

```{r}
plot(point_cloud)
plot(point_cloud,color="UserData")
tree_only<-lasfilter(point_cloud,!point_cloud@data$UserData)
plot(tree_only,color="UserData")
```

```{r}
las<-readLAS("/Users/Ben/Documents/DeepLidar/data/NIWO/plots/NIWO_042.laz")
las <- lasnormalize(las = las,algorithm = knnidw(k = 8, p = 2))
las<-lasfilter(las,Z < 40)
plot(las)
```

## Compute Height Model

```{r}
chm <- lidR::grid_canopy(las, res = 0.5, lidR::pitfree(c(0,2,5,10,15), c(0, 1.5)))
plot(chm)

```

# View annotations
